export const ROUTES = {
  GRAPH: '/',
  ENCYCLOPEDIA: '/encyclopedia',
  ENTITY: '/entity/:slug',
  CLAIM: '/claim/:id',
  SOURCES: '/sources',
  SOURCE_DETAIL: '/source/:id',
  SEARCH: '/search',
  EXPLORATIONS: '/explorations',
  EXPLORATION_PLAYER: '/explorations/:id',
  TIMELINE: '/timeline',
  COMPARE: '/compare',
  ADMIN_LOGIN: '/admin/login',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_SOURCES: '/admin/sources',
  ADMIN_SOURCE_NEW: '/admin/sources/new',
  ADMIN_SOURCE_DETAIL: '/admin/sources/:id',
  ADMIN_SOURCE_IMPACT: '/admin/sources/:id/impact',
  ADMIN_REVIEW: '/admin/review',
  ADMIN_ENTITIES: '/admin/entities',
  ADMIN_CLAIMS: '/admin/claims',
  ADMIN_RELATIONSHIPS: '/admin/relationships',
  ADMIN_SETTINGS: '/admin/settings',
  ADMIN_URL_DOMAINS: '/admin/settings/url-domains',
  ADMIN_EXPLORATION_NEW: '/admin/explorations/new',
} as const
