export const ROUTES = {
  GRAPH: '/',
  ENCYCLOPEDIA: '/encyclopedia',
  ENTITY: '/entity/:slug',
  CLAIM: '/claim/:id',
  SOURCES: '/sources',
  SOURCE_DETAIL: '/source/:id',
  SEARCH: '/search',
  ADMIN_LOGIN: '/admin/login',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_SOURCES: '/admin/sources',
  ADMIN_SOURCE_NEW: '/admin/sources/new',
  ADMIN_REVIEW: '/admin/review',
  ADMIN_ENTITIES: '/admin/entities',
  ADMIN_CLAIMS: '/admin/claims',
  ADMIN_SETTINGS: '/admin/settings',
} as const
